import os
import requests
from dotenv import load_dotenv
import logging

load_dotenv()
logger = logging.getLogger(__name__)

class GeminiImageAPI:
    def __init__(self):
        self.api_key = os.environ.get("GEMINI_IMAGE_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_IMAGE_API_KEY is missing[span_19](start_span)[span_19](end_span).")
        
    def generate_featured_image(self, topic: str, style: str = "Editorial, Professional, High Quality, Finance concept art") -> bytes:
        """Generates an image using Google's Imagen/Gemini API endpoint[span_20](start_span)[span_20](end_span)."""
        prompt = f"Create a professional blog featured image for the finance topic: {topic}. Style: {style}. No text or words in the image."
        
        # Note: As of current Google GenAI SDK, Image generation might require Vertex AI or specific Imagen REST endpoints.
        # This is a representative REST implementation for Google Imagen API.
        url = f"[https://generativelanguage.googleapis.com/v1beta/models/image-generation:generateImages?key=](https://generativelanguage.googleapis.com/v1beta/models/image-generation:generateImages?key=){self.api_key}"
        
        headers = {"Content-Type": "application/json"}
        payload = {
            "prompt": prompt,
            "imageCount": 1,
            "outputOptions": {"mimeType": "image/jpeg"}
        }
        
        try:
            logger.info(f"Generating image for topic: {topic}")
            response = requests.post(url, json=payload, headers=headers)
            response.raise_for_status()
            
            data = response.json()
            if 'images' in data and len(data['images']) > 0:
                import base64
                image_data = data['images'][0]['image']['imageBytes']
                return base64.b64decode(image_data)
            else:
                raise ValueError("No image generated by API.")
                
        except Exception as e:
            logger.error(f"Image API Error: {e}")
            raise e
          
